# -*- coding: utf-8 -*-
"""05_generate_embeddings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTJoid1eU1aeEonxM5_E8INTf_KUnQPE
"""

import torch

print("GPU Available :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU :", torch.cuda.get_device_name(0))

!pip -q install boto3 s3fs pyarrow pandas sentence-transformers tqdm

import os

os.environ["AWS_ACCESS_KEY_ID"] = "ASIAZQ3DULKJU2LCIER7"
os.environ["AWS_SECRET_ACCESS_KEY"] = "9euBCF7wFIblziSAiWddgEAPFecNI5k2f6D+t1WG"
os.environ["AWS_SESSION_TOKEN"] = "IQoJb3JpZ2luX2VjENL//////////wEaCXVzLXdlc3QtMiJHMEUCIG3cWDbotwOnOZ/MsFA+bBNaaDzSW5q7DxgSex3oVsRBAiEAzHk6M8QDTHLucPNAHTO54AlogIikQWnz5/3zs8tJ+JsqvAIImv//////////ARAAGgw2NTQ2NTQ1OTM2ODMiDFlaFbojsPr/ZeAcHSqQAsVItWuregAZ+f2Uog9RQzGmZQucNt+Si5ggz/BSG8rJript4D1RKryR/UmJUxiFbIjB1hsYB2+ZS3tz0OWIf9zd4Q5J+Ia24SqWsMw2AKAJ7kZGAuzT8GwYfAXJtW3n4w5XahHEnUx95plbBPn6Lz1MFbOj3yfaiUR7Ry0tt9Ur7xfWegX+ALUbOtmGZN4jWB5a0sRPae1U+x+xjpTuTKVE32vrgXxm2IQh+6zNo1vBX8y1s/guzxMN/mnQiIAMDqGYdWgnsa+qnt4nI5W/g5rHF4Ig71y8/Mz6tzGZYYk/RInYn7AOeQanam7qba272rdTRDgextnEbB9xPYZoD13nNNvWU1wI+eaWpYv2Wt+CMIOQrtMGOp0BdBi/S+Nee7bvBjFIh65nJqJdCMgb316mixiahmaTSR+PxHGCLXB7fOVe7dTDyZV2ofEAsnfq/NkHhqOzfW0EA8fcIwL4A0qlCtkSf3kGplKdssFTSR2mm+sSgDZJ342SD6pbkUCRtB3R3qMK27lYZShi+kjnB0nimcp6IhgBgVUGJUsjVbtpU/nDVQHGCowoASXhBvu0zWRvVM9Sbw=="
os.environ["AWS_DEFAULT_REGION"] = "us-east-1"   # Change if your lab uses another region

import os

print("Access Key :", os.environ.get("AWS_ACCESS_KEY_ID") is not None)
print("Secret Key :", os.environ.get("AWS_SECRET_ACCESS_KEY") is not None)
print("Session Token :", os.environ.get("AWS_SESSION_TOKEN") is not None)
print("Region :", os.environ.get("AWS_DEFAULT_REGION"))

import boto3

session = boto3.Session(
    aws_access_key_id="ASIAZQ3DULKJU2LCIER7",
    aws_secret_access_key="9euBCF7wFIblziSAiWddgEAPFecNI5k2f6D+t1WG",
    aws_session_token="IQoJb3JpZ2luX2VjENL//////////wEaCXVzLXdlc3QtMiJHMEUCIG3cWDbotwOnOZ/MsFA+bBNaaDzSW5q7DxgSex3oVsRBAiEAzHk6M8QDTHLucPNAHTO54AlogIikQWnz5/3zs8tJ+JsqvAIImv//////////ARAAGgw2NTQ2NTQ1OTM2ODMiDFlaFbojsPr/ZeAcHSqQAsVItWuregAZ+f2Uog9RQzGmZQucNt+Si5ggz/BSG8rJript4D1RKryR/UmJUxiFbIjB1hsYB2+ZS3tz0OWIf9zd4Q5J+Ia24SqWsMw2AKAJ7kZGAuzT8GwYfAXJtW3n4w5XahHEnUx95plbBPn6Lz1MFbOj3yfaiUR7Ry0tt9Ur7xfWegX+ALUbOtmGZN4jWB5a0sRPae1U+x+xjpTuTKVE32vrgXxm2IQh+6zNo1vBX8y1s/guzxMN/mnQiIAMDqGYdWgnsa+qnt4nI5W/g5rHF4Ig71y8/Mz6tzGZYYk/RInYn7AOeQanam7qba272rdTRDgextnEbB9xPYZoD13nNNvWU1wI+eaWpYv2Wt+CMIOQrtMGOp0BdBi/S+Nee7bvBjFIh65nJqJdCMgb316mixiahmaTSR+PxHGCLXB7fOVe7dTDyZV2ofEAsnfq/NkHhqOzfW0EA8fcIwL4A0qlCtkSf3kGplKdssFTSR2mm+sSgDZJ342SD6pbkUCRtB3R3qMK27lYZShi+kjnB0nimcp6IhgBgVUGJUsjVbtpU/nDVQHGCowoASXhBvu0zWRvVM9Sbw==",
    region_name="us-east-1"
)

sts = session.client("sts")
print(sts.get_caller_identity())

s3 = session.client("s3")

try:
    print(s3.head_bucket(Bucket="ml-data-aws-transformer-bert"))
    print("Bucket exists and is accessible.")

except ClientError as e:
    print(e.response["Error"]["Code"])
    print(e.response["Error"]["Message"])

response = s3.list_objects_v2(
    Bucket="ml-data-aws-transformer-bert",
    Prefix="ml/preprocessing/final_documents/",
    MaxKeys=10
)

print(response)

response = s3.list_objects_v2(
    Bucket="ml-data-aws-transformer-bert",
    Prefix="ml/preprocessing/final_documents/"
)

for obj in response.get("Contents", []):
    print(obj["Key"])

!pip install -q s3fs pyarrow

import time
import pandas as pd

start = time.time()

df = pd.read_parquet(
    "s3://ml-data-aws-transformer-bert/ml/preprocessing/final_documents/",
    storage_options={
        "key": "ASIAZQ3DULKJU2LCIER7",
        "secret": "9euBCF7wFIblziSAiWddgEAPFecNI5k2f6D+t1WG",
        "token": "IQoJb3JpZ2luX2VjENL//////////wEaCXVzLXdlc3QtMiJHMEUCIG3cWDbotwOnOZ/MsFA+bBNaaDzSW5q7DxgSex3oVsRBAiEAzHk6M8QDTHLucPNAHTO54AlogIikQWnz5/3zs8tJ+JsqvAIImv//////////ARAAGgw2NTQ2NTQ1OTM2ODMiDFlaFbojsPr/ZeAcHSqQAsVItWuregAZ+f2Uog9RQzGmZQucNt+Si5ggz/BSG8rJript4D1RKryR/UmJUxiFbIjB1hsYB2+ZS3tz0OWIf9zd4Q5J+Ia24SqWsMw2AKAJ7kZGAuzT8GwYfAXJtW3n4w5XahHEnUx95plbBPn6Lz1MFbOj3yfaiUR7Ry0tt9Ur7xfWegX+ALUbOtmGZN4jWB5a0sRPae1U+x+xjpTuTKVE32vrgXxm2IQh+6zNo1vBX8y1s/guzxMN/mnQiIAMDqGYdWgnsa+qnt4nI5W/g5rHF4Ig71y8/Mz6tzGZYYk/RInYn7AOeQanam7qba272rdTRDgextnEbB9xPYZoD13nNNvWU1wI+eaWpYv2Wt+CMIOQrtMGOp0BdBi/S+Nee7bvBjFIh65nJqJdCMgb316mixiahmaTSR+PxHGCLXB7fOVe7dTDyZV2ofEAsnfq/NkHhqOzfW0EA8fcIwL4A0qlCtkSf3kGplKdssFTSR2mm+sSgDZJ342SD6pbkUCRtB3R3qMK27lYZShi+kjnB0nimcp6IhgBgVUGJUsjVbtpU/nDVQHGCowoASXhBvu0zWRvVM9Sbw=="
    }
)

print(df.shape)
print("Time:", time.time() - start)

print("="*60)
print("Dataset Shape")
print("="*60)

print(df.shape)

print("="*60)
print("Columns")
print("="*60)

print(df.columns.tolist())

print("="*60)
print("Data Types")
print("="*60)

print(df.dtypes)

print("="*60)
print("Dataset Info")
print("="*60)

df.info(memory_usage="deep")

print("="*60)
print("First Five Rows")
print("="*60)

display(df.head())

print("="*60)
print("Random Sample")
print("="*60)

display(df.sample(5, random_state=42))

print("="*60)
print("Missing Values")
print("="*60)

print(df.isnull().sum())

empty_docs = (df["document"].astype(str).str.strip() == "").sum()

print("Empty Documents :", empty_docs)

print("Duplicate parent_asin :")

print(df["parent_asin"].duplicated().sum())

print("Duplicate Documents :")

print(df["document"].duplicated().sum())

print("="*60)
print("Category Distribution")
print("="*60)

print(df["category"].value_counts())

doc_length = df["document"].astype(str).str.len()

print(doc_length.describe())

df["doc_length"] = df["document"].astype(str).str.len()

display(
    df[["parent_asin","product_title","doc_length"]]
    .sort_values("doc_length", ascending=False)
    .head(10)
)

print("Average Length")

print(df["document"].astype(str).str.len().mean())

small_docs = df[df["document"].astype(str).str.len() < 20]

print("Documents shorter than 20 chars:")

print(len(small_docs))

large_docs = df[df["document"].astype(str).str.len() > 8000]

print("Documents longer than 8000 chars:")

print(len(large_docs))

print(df.iloc[0]["document"])

print("="*60)
print("Memory Usage")
print("="*60)

print(df.memory_usage(deep=True))

print("="*60)
print("FINAL CHECK")
print("="*60)

print("Rows :", len(df))
print("Columns :", len(df.columns))
print("Null Documents :", df["document"].isna().sum())
print("Empty Documents :", (df["document"].astype(str).str.strip()=="").sum())
print("Unique Products :", df["parent_asin"].nunique())

!pip install -q sentence-transformers transformers accelerate tqdm

from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2",
    device="cuda"
)

sample_df = df.sample(
    n=5000,
    random_state=42
).reset_index(drop=True)

import torch

print(torch.cuda.get_device_name(0))
print(torch.cuda.get_device_properties(0).total_memory/1024**3,"GB")

import time

start = time.time()

embeddings = model.encode(
    sample_df["document"].tolist(),
    batch_size=256,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

end = time.time()

print("Embedding Shape :", embeddings.shape)
print("Total Time :", end-start)
print("Docs/sec :", len(sample_df)/(end-start))

embeddings = model.encode(
    sample_df["document"].tolist(),
    batch_size=512,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

import boto3

session = boto3.Session(
    aws_access_key_id="ASIAZQ3DULKJU2LCIER7",
    aws_secret_access_key="9euBCF7wFIblziSAiWddgEAPFecNI5k2f6D+t1WG",
    aws_session_token="IQoJb3JpZ2luX2VjENL//////////wEaCXVzLXdlc3QtMiJHMEUCIG3cWDbotwOnOZ/MsFA+bBNaaDzSW5q7DxgSex3oVsRBAiEAzHk6M8QDTHLucPNAHTO54AlogIikQWnz5/3zs8tJ+JsqvAIImv//////////ARAAGgw2NTQ2NTQ1OTM2ODMiDFlaFbojsPr/ZeAcHSqQAsVItWuregAZ+f2Uog9RQzGmZQucNt+Si5ggz/BSG8rJript4D1RKryR/UmJUxiFbIjB1hsYB2+ZS3tz0OWIf9zd4Q5J+Ia24SqWsMw2AKAJ7kZGAuzT8GwYfAXJtW3n4w5XahHEnUx95plbBPn6Lz1MFbOj3yfaiUR7Ry0tt9Ur7xfWegX+ALUbOtmGZN4jWB5a0sRPae1U+x+xjpTuTKVE32vrgXxm2IQh+6zNo1vBX8y1s/guzxMN/mnQiIAMDqGYdWgnsa+qnt4nI5W/g5rHF4Ig71y8/Mz6tzGZYYk/RInYn7AOeQanam7qba272rdTRDgextnEbB9xPYZoD13nNNvWU1wI+eaWpYv2Wt+CMIOQrtMGOp0BdBi/S+Nee7bvBjFIh65nJqJdCMgb316mixiahmaTSR+PxHGCLXB7fOVe7dTDyZV2ofEAsnfq/NkHhqOzfW0EA8fcIwL4A0qlCtkSf3kGplKdssFTSR2mm+sSgDZJ342SD6pbkUCRtB3R3qMK27lYZShi+kjnB0nimcp6IhgBgVUGJUsjVbtpU/nDVQHGCowoASXhBvu0zWRvVM9Sbw==",
    region_name="us-east-1"
)

s3 = session.client("s3")

s3.put_object(
    Bucket="ml-data-aws-transformer-bert",
    Key="ml/embeddings/"
)

print("Embeddings folder created.")

CHUNK_SIZE = 50000

num_chunks = (len(df) + CHUNK_SIZE - 1) // CHUNK_SIZE

print(num_chunks)

chunk = df.iloc[:CHUNK_SIZE].copy()

print(chunk.shape)

chunk.columns

chunk = chunk.drop(columns=["doc_length"], errors="ignore")

print(chunk.shape)

chunk = df.iloc[:CHUNK_SIZE].copy()

chunk = (
    df.iloc[:CHUNK_SIZE]
      .drop(columns=["doc_length"], errors="ignore")
      .reset_index(drop=True)
)

import time

start = time.time()

embeddings = model.encode(
    chunk["document"].tolist(),
    batch_size=512,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

end = time.time()

print("Embedding Shape:", embeddings.shape)
print("Time:", end - start)

import pandas as pd

embedding_df = pd.DataFrame({
    "parent_asin": chunk["parent_asin"],
    "category": chunk["category"],
    "product_title": chunk["product_title"],
    "embedding": embeddings.tolist()
})

embedding_df.head()

print(embedding_df.shape)

embedding_df.info()

embedding_df.to_parquet(
    "embedding_chunk_001.parquet",
    index=False
)

import os

print(os.path.getsize("embedding_chunk_001.parquet")/1024/1024, "MB")

test = pd.read_parquet("embedding_chunk_001.parquet")

test.head()

print(test.shape)

s3.upload_file(
    "embedding_chunk_001.parquet",
    "ml-data-aws-transformer-bert",
    "ml/embeddings/all_minilm_l6_v2/embedding_chunk_001.parquet"
)

print("Upload Successful")

response = s3.list_objects_v2(
    Bucket="ml-data-aws-transformer-bert",
    Prefix="ml/embeddings/all_minilm_l6_v2/"
)

for obj in response.get("Contents", []):
    print(obj["Key"])

import math
import gc
import torch
import pandas as pd
from tqdm import tqdm

CHUNK_SIZE = 50000

TOTAL_ROWS = len(df)

TOTAL_CHUNKS = math.ceil(TOTAL_ROWS / CHUNK_SIZE)

print("Total Rows :", TOTAL_ROWS)
print("Chunk Size :", CHUNK_SIZE)
print("Total Chunks :", TOTAL_CHUNKS)

import time
import gc
import torch

for chunk_id in range(1, TOTAL_CHUNKS):

    print("=" * 80)
    print(f"Processing Chunk {chunk_id + 1}/{TOTAL_CHUNKS}")

    start_idx = chunk_id * CHUNK_SIZE
    end_idx = min((chunk_id + 1) * CHUNK_SIZE, TOTAL_ROWS)

    chunk = (
        df.iloc[start_idx:end_idx]
        .drop(columns=["doc_length"], errors="ignore")
        .reset_index(drop=True)
    )

    start = time.time()

    embeddings = model.encode(
        chunk["document"].tolist(),
        batch_size=512,
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True
    )

    embedding_df = pd.DataFrame({
        "parent_asin": chunk["parent_asin"],
        "category": chunk["category"],
        "product_title": chunk["product_title"],
        "embedding": embeddings.tolist()
    })

    output_file = f"embedding_chunk_{chunk_id + 1:03d}.parquet"

    embedding_df.to_parquet(output_file, index=False)

    s3.upload_file(
        output_file,
        "ml-data-aws-transformer-bert",
        f"ml/embeddings/all_minilm_l6_v2/{output_file}"
    )

    end = time.time()

    print(f"Chunk {chunk_id + 1} completed.")
    print(f"Rows : {len(chunk)}")
    print(f"Time : {round(end-start,2)} sec")

    del chunk
    del embeddings
    del embedding_df

    gc.collect()
    torch.cuda.empty_cache()

print("=" * 80)
print("ALL EMBEDDINGS GENERATED SUCCESSFULLY")

response = s3.list_objects_v2(
    Bucket="ml-data-aws-transformer-bert",
    Prefix="ml/embeddings/all_minilm_l6_v2/"
)

for obj in response.get("Contents", []):
    print(obj["Key"], round(obj["Size"] / 1024 / 1024, 2), "MB")

test = pd.read_parquet(
    "s3://ml-data-aws-transformer-bert/ml/embeddings/all_minilm_l6_v2/embedding_chunk_005.parquet",
    storage_options={
        "key": "ASIAZQ3DULKJU2LCIER7",
        "secret": "9euBCF7wFIblziSAiWddgEAPFecNI5k2f6D+t1WG",
        "token": "IQoJb3JpZ2luX2VjENL//////////wEaCXVzLXdlc3QtMiJHMEUCIG3cWDbotwOnOZ/MsFA+bBNaaDzSW5q7DxgSex3oVsRBAiEAzHk6M8QDTHLucPNAHTO54AlogIikQWnz5/3zs8tJ+JsqvAIImv//////////ARAAGgw2NTQ2NTQ1OTM2ODMiDFlaFbojsPr/ZeAcHSqQAsVItWuregAZ+f2Uog9RQzGmZQucNt+Si5ggz/BSG8rJript4D1RKryR/UmJUxiFbIjB1hsYB2+ZS3tz0OWIf9zd4Q5J+Ia24SqWsMw2AKAJ7kZGAuzT8GwYfAXJtW3n4w5XahHEnUx95plbBPn6Lz1MFbOj3yfaiUR7Ry0tt9Ur7xfWegX+ALUbOtmGZN4jWB5a0sRPae1U+x+xjpTuTKVE32vrgXxm2IQh+6zNo1vBX8y1s/guzxMN/mnQiIAMDqGYdWgnsa+qnt4nI5W/g5rHF4Ig71y8/Mz6tzGZYYk/RInYn7AOeQanam7qba272rdTRDgextnEbB9xPYZoD13nNNvWU1wI+eaWpYv2Wt+CMIOQrtMGOp0BdBi/S+Nee7bvBjFIh65nJqJdCMgb316mixiahmaTSR+PxHGCLXB7fOVe7dTDyZV2ofEAsnfq/NkHhqOzfW0EA8fcIwL4A0qlCtkSf3kGplKdssFTSR2mm+sSgDZJ342SD6pbkUCRtB3R3qMK27lYZShi+kjnB0nimcp6IhgBgVUGJUsjVbtpU/nDVQHGCowoASXhBvu0zWRvVM9Sbw=="
    }
)

test.head()

print(test.shape)

test.isnull().sum()

len(test.iloc[0]["embedding"])

dims = test["embedding"].apply(len)

print(dims.value_counts())

test.info()

test["parent_asin"].duplicated().sum()

embedding_strings = test["embedding"].astype(str)

print(embedding_strings.duplicated().sum())

import numpy as np

emb = np.array(test.iloc[0]["embedding"])

print("Minimum :", emb.min())
print("Maximum :", emb.max())
print("Mean    :", emb.mean())
print("Std     :", emb.std())

normalize_embeddings=True

import numpy as np

norm = np.linalg.norm(np.array(test.iloc[0]["embedding"]))

print(norm)

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

v1 = np.array(test.iloc[0]["embedding"]).reshape(1, -1)
v2 = np.array(test.iloc[1]["embedding"]).reshape(1, -1)

print(cosine_similarity(v1, v2))

total = 0

for i in range(1, 10):

    file = f"s3://ml-data-aws-transformer-bert/ml/embeddings/all_minilm_l6_v2/embedding_chunk_{i:03d}.parquet"

    chunk = pd.read_parquet(
        file,
        storage_options={
            "key": "ASIAZQ3DULKJU2LCIER7",
            "secret": "9euBCF7wFIblziSAiWddgEAPFecNI5k2f6D+t1WG",
            "token": "IQoJb3JpZ2luX2VjENL//////////wEaCXVzLXdlc3QtMiJHMEUCIG3cWDbotwOnOZ/MsFA+bBNaaDzSW5q7DxgSex3oVsRBAiEAzHk6M8QDTHLucPNAHTO54AlogIikQWnz5/3zs8tJ+JsqvAIImv//////////ARAAGgw2NTQ2NTQ1OTM2ODMiDFlaFbojsPr/ZeAcHSqQAsVItWuregAZ+f2Uog9RQzGmZQucNt+Si5ggz/BSG8rJript4D1RKryR/UmJUxiFbIjB1hsYB2+ZS3tz0OWIf9zd4Q5J+Ia24SqWsMw2AKAJ7kZGAuzT8GwYfAXJtW3n4w5XahHEnUx95plbBPn6Lz1MFbOj3yfaiUR7Ry0tt9Ur7xfWegX+ALUbOtmGZN4jWB5a0sRPae1U+x+xjpTuTKVE32vrgXxm2IQh+6zNo1vBX8y1s/guzxMN/mnQiIAMDqGYdWgnsa+qnt4nI5W/g5rHF4Ig71y8/Mz6tzGZYYk/RInYn7AOeQanam7qba272rdTRDgextnEbB9xPYZoD13nNNvWU1wI+eaWpYv2Wt+CMIOQrtMGOp0BdBi/S+Nee7bvBjFIh65nJqJdCMgb316mixiahmaTSR+PxHGCLXB7fOVe7dTDyZV2ofEAsnfq/NkHhqOzfW0EA8fcIwL4A0qlCtkSf3kGplKdssFTSR2mm+sSgDZJ342SD6pbkUCRtB3R3qMK27lYZShi+kjnB0nimcp6IhgBgVUGJUsjVbtpU/nDVQHGCowoASXhBvu0zWRvVM9Sbw=="
        }
    )

    print(i, chunk.shape)

    total += len(chunk)

print("Total Rows =", total)

