from pathlib import Path

import numpy as np
import pandas as pd

import chromadb


# Chroma Builder
class ChromaBuilder:
    """
    Builds a persistent ChromaDB collection
    for semantic product retrieval.
    """

    def __init__(
            self,
            embedding_file,
            metadata_file,
            sentiment_file,
            output_dir,
            batch_size=1000
    ):
        self.embedding_file = Path(
            embedding_file
        )

        self.metadata_file = Path(
            metadata_file
        )

        self.sentiment_file = Path(
            sentiment_file
        )

        self.output_dir = Path(
            output_dir
        )

        self.output_dir.mkdir(
            parents=True,
            exist_ok=True
        )

        self.chroma_dir = (
                self.output_dir /
                "chroma_db"
        )

        self.chroma_dir.mkdir(
            parents=True,
            exist_ok=True
        )

        self.batch_size = batch_size

        self.embeddings = None

        self.metadata = None

        self.sentiment = None

        self.products = None

        self.documents = None

        self.ids = None

        self.metadatas = None

        self.client = None

        self.collection = None

    # Load Embeddings
    def load_embeddings(self):
        """
        Loads product embeddings
        generated by EmbeddingProcessor.
        """

        print("=" * 60)
        print("LOADING PRODUCT EMBEDDINGS")
        print("=" * 60)

        self.embeddings = np.load(
            self.embedding_file
        ).astype(np.float32)

        print(
            "Embeddings Loaded Successfully"
        )

        print(
            f"Embedding Shape : {self.embeddings.shape}"
        )

        print(
            f"Embedding Dimension : {self.embeddings.shape[1]}"
        )

        print(
            f"Total Products : {self.embeddings.shape[0]:,}"
        )

    # Load Metadata
    def load_metadata(self):
        """
        Loads product metadata
        and product sentiment.
        """

        print("=" * 60)
        print("LOADING PRODUCT METADATA")
        print("=" * 60)

        self.metadata = pd.read_parquet(
            self.metadata_file
        )

        self.sentiment = pd.read_parquet(
            self.sentiment_file
        )

        print(
            "Metadata Loaded Successfully"
        )

        print(
            f"Metadata Records  : {len(self.metadata):,}"
        )

        print(
            f"Sentiment Records : {len(self.sentiment):,}"
        )

    # Merge Metadata
    def merge_metadata(self):
        """
        Merges product metadata
        with product sentiment.
        """

        print("=" * 60)
        print("MERGING PRODUCT METADATA")
        print("=" * 60)

        self.products = self.metadata.merge(
            self.sentiment,
            on="parent_asin",
            how="inner",
            suffixes=("", "_sentiment")
        )

        print(
            "Metadata Merged Successfully"
        )

        print(
            f"Total Products : {len(self.products):,}"
        )

        # Free Memory
        del self.metadata
        del self.sentiment

    # Create Documents
    # Create Documents
    def create_documents(self):
        """
        Creates semantic documents,
        metadata and IDs for
        every product.
        """

        print("=" * 60)
        print("CREATING DOCUMENTS")
        print("=" * 60)

        self.products = self.products.fillna("")

        self.documents = []

        self.ids = []

        self.metadatas = []

        for row in self.products.itertuples(index=False):
            # Create Document
            document = (
                f"Title: {row.product_title}\n\n"
                f"Brand: {row.store}\n\n"
                f"Category: {row.main_category}\n\n"
                f"Sub Category: {row.sub_category}\n\n"
                f"Description:\n"
                f"{row.description_text}\n\n"
                f"Features:\n"
                f"{row.features_text}"
            )

            # Store Document
            self.documents.append(
                document.strip()
            )

            # Store Product ID
            self.ids.append(
                row.parent_asin
            )

            # Store Metadata
            self.metadatas.append(
                {
                    "product_title": row.product_title,

                    "store": row.store,

                    "main_category": row.main_category,

                    "sub_category": row.sub_category,

                    "product_average_rating": float(
                        row.product_average_rating
                    ),

                    "product_rating_count": int(
                        row.product_rating_count
                    ),

                    "product_sentiment": row.product_sentiment,

                    "product_image_url": row.product_image_url
                }
            )

        print(
            f"Documents Created : {len(self.documents):,}"
        )

        print(
            f"Metadata Created : {len(self.metadatas):,}"
        )

        print(
            f"IDs Created : {len(self.ids):,}"
        )
    # Create Chroma Client
    def create_chroma_client(self):
        """
        Creates a persistent
        ChromaDB client.
        """

        print("=" * 60)
        print("CREATING CHROMADB CLIENT")
        print("=" * 60)

        self.client = chromadb.PersistentClient(
            path=str(
                self.chroma_dir
            )
        )

        print(
            "ChromaDB Client Created Successfully"
        )

        print(
            f"Database Path : {self.chroma_dir}"
        )

    # Create Collection
    def create_collection(self):
        """
        Creates a fresh
        ChromaDB collection.
        """

        print("=" * 60)
        print("CREATING COLLECTION")
        print("=" * 60)

        try:
            self.client.delete_collection(
                "amazon_products"
            )

            print(
                "Existing Collection Deleted"
            )

        except Exception:
            pass

        self.collection = self.client.create_collection(
            name="amazon_products",
            metadata={
                "description":
                    "Amazon Product Recommendation Collection"
            }
        )

        print(
            "Collection Created Successfully"
        )

        print(
            f"Collection Name : {self.collection.name}"
        )

    # Insert Products
    # Insert Products
    def insert_products(self):
        """
        Inserts products into
        ChromaDB in batches.
        """

        print("=" * 60)
        print("INSERTING PRODUCTS")
        print("=" * 60)

        total_products = len(self.ids)

        batch_number = 1
        assert (
                len(self.ids)
                == len(self.documents)
                == len(self.metadatas)
                == len(self.embeddings)
        ), "Mismatch between embeddings, documents, IDs and metadata."
        for start in range(
                0,
                total_products,
                self.batch_size
        ):

            end = min(
                start + self.batch_size,
                total_products
            )

            self.collection.add(

                ids=self.ids[start:end],

                documents=self.documents[start:end],

                embeddings=self.embeddings[
                    start:end
                ].tolist(),

                metadatas=self.metadatas[
                    start:end
                ]
            )

            # Print progress every 10 batches
            if (
                    batch_number % 10 == 0
                    or
                    end == total_products
            ):
                print(
                    f"Batch {batch_number} Completed "
                    f"({end:,}/{total_products:,})"
                )

            batch_number += 1

        print()

        print(
            "All Products Inserted Successfully"
        )

        # Free Memory
        del self.documents

        del self.ids

        del self.metadatas

        del self.embeddings

        del self.products


    # Verify Collection
    def verify_collection(self):
        """
        Verifies the ChromaDB
        collection.
        """

        print("=" * 60)
        print("VERIFYING COLLECTION")
        print("=" * 60)

        total_products = self.collection.count()

        print(
            f"Total Products Stored : {total_products:,}"
        )

        # Retrieve one sample record
        sample = self.collection.peek(
            limit=1
        )

        print("\nSample Product")

        print(
            f"ID : {sample['ids'][0]}"
        )

        print(
            f"Metadata : {sample['metadatas'][0]}"
        )

        print(
            f"Document :\n{sample['documents'][0]}"
        )

        print(
            "Collection Verified Successfully"
        )
        del sample
    # Complete Pipeline
    def process(self):
        """
        Runs complete ChromaDB
        build pipeline.
        """

        self.load_embeddings()

        self.load_metadata()

        self.merge_metadata()

        self.create_documents()

        self.create_chroma_client()

        self.create_collection()

        self.insert_products()

        self.verify_collection()
if __name__ == "__main__":

    builder = ChromaBuilder(

        embedding_file="../outputs/product_embeddings.npy",

        metadata_file="../outputs/product_metadata.parquet",

        sentiment_file="../outputs/product_sentiment.parquet",

        output_dir="../outputs",

        batch_size=1000
    )

    builder.process()
