project:
  name: "Amazon Review Analytics"

aws:
  region: "us-east-1"
  bucket_name: "amazon-review-analytics-group-2"

# ==========================================================
# S3 Paths
# ==========================================================

paths:
  cleaned: "gold/ml-hybrid-rag/cleaned"
  product_documents: "gold/ml-hybrid-rag/product_documents"
  embeddings: "gold/ml-hybrid-rag/embeddings"
  bm25: "gold/ml-hybrid-rag/bm25"
  chromadb_backup: "gold/ml-hybrid-rag/chromadb_backup"

# ==========================================================
# Embedding Configuration
# ==========================================================

embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  dimension: 384
  batch_size: 32
  normalize_embeddings: true
  show_progress_bar: true

# ==========================================================
# Review Selection
# ==========================================================

review_selection:
  helpful_reviews: 10
  recent_reviews: 5

# ==========================================================
# ChromaDB
# ==========================================================

chromadb:
  persist_directory: "/home/hadoop/ml-hybrid-rag/chromadb"

# ==========================================================
# Retrieval
# ==========================================================

retrieval:
  top_k_semantic: 10
  top_k_bm25: 10
  final_top_k: 5
  normalize_query_embeddings: true

# ==========================================================
# BM25
# ==========================================================

bm25:
  lowercase: true

# ==========================================================
# Reranker
# ==========================================================

reranker:
  model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  batch_size: 32
  max_length: 512
  show_progress_bar: false

# ==========================================================
# Gemini
# ==========================================================

gemini:
  model_name: "gemini-2.5-flash"
  temperature: 0.2