name: Deploy to Development

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}
  S3_ARTIFACT_PREFIX: ${{ vars.S3_ARTIFACT_PREFIX }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Validate Project
        run: |
          chmod +x scripts/build/build.sh
          ./scripts/build/build.sh

      - name: Package Project
        run: |
          chmod +x scripts/build/package.sh
          ./scripts/build/package.sh

      - name: Upload GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: amazon-review-analytics-platform
          path: build/amazon-review-analytics-platform.zip

      - name: Deploy to S3
        run: |
          chmod +x scripts/deploy/deploy-dev.sh
          ./scripts/deploy/deploy-dev.sh